# Generated by Django 2.2 on 2019-04-29 17:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('vlow', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20)),
                ('low', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20)),
                ('nom', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20)),
                ('high', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20)),
                ('vhigh', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20)),
                ('ehigh', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20)),
            ],
        ),
    ]
